### ISSUE TITLE
如何得到绘制的坐标点信息

### ISSUE THREAD

**Issue by caichunjian520** [woodemi/notepad-example-ios#5]
目前看到只能连接断开获取设备信息么，如何获取到绘制的坐标点呢？

**Comment by Sunbreak** [comment]
Readme中没写，其实代码中各种功能都有的，其他问题可以咨询微信woodemi

> Android的Readme更完整：https://github.com/woodemi/notepad-example-android

# Sync notepen pointer

## NotepadClient#setMode

https://github.com/woodemi/notepad-example-ios/blob/master/notepad-example-ios/NotepadDetailViewController.swift#L86

```swift
notepadClient?.setMode(to: .sync, complete: {
    print("setMode complete")
}) {
    print("setMode error \($0.description)")
}
```

## NotepadClient.Callback#handlePointer

https://github.com/woodemi/notepad-example-ios/blob/master/notepad-example-ios/NotepadDetailViewController.swift#L217

```swift
func handlePointer(list: [NotePenPointer]) {
    print("handlePointer \(list.count)")
}
```

**Comment by caichunjian520** [comment]
非常感谢
